package com.smartqueue.entity;

public enum NotificationType {
    QUEUE_JOINED, TURN_APPROACHING, YOUR_TURN, QUEUE_CLOSED, HOLD_EXPIRING, TOKEN_CANCELLED, TOKEN_COMPLETED, PRIORITY_CHANGED, GENERAL
}
